apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: spring-sensors-consumer-web.default.tap-pkgi
spec:
  packageRef:
    refName: spring-sensors-consumer-web.default.tap
    versionSelection:
      constraints: 20240402101850.0.0
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: spring-sensors-consumer-web.default.tap-values
