apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  labels:
    carto.run/workload-name: spring-sensors-producer
  name: spring-sensors-producer-rmq
spec:
  name: rmq
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: rabbitmq-1
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: spring-sensors-producer
