apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: override-feature-gitops.default.tap-pkgi
spec:
  packageRef:
    refName: override-feature-gitops.default.tap
    versionSelection:
      constraints: 20240408131203.0.0
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: override-feature-gitops.default.tap-values
