apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-java-web-app.default.tap-pkgi
spec:
  packageRef:
    refName: tanzu-java-web-app.default.tap
    versionSelection:
      constraints: 20240322133119.0.0
      prereleases: {}
  serviceAccountName: default
  values:
  - secretRef:
      name: tanzu-java-web-app.default.tap-values
